// Generates mirea-deck.html from slide data.
// Run: node tools/build-deck.mjs (executed inside the project sandbox via run_script)

export const SLIDES = [
  // ============= COVER =============
  { kind: 'cover', label: '01 Титул' },

  // ============= INTRO =============
  {
    kind: 'content', label: '02 Актуальность', section: 'Раздел 1 · Постановка задачи',
    eyebrow: 'Раздел 1 · Постановка задачи', title: 'Актуальность',
    meta: 'КОНТЕКСТ',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'actuality',
  },
  {
    kind: 'content', label: '03 Цели и задачи',
    eyebrow: 'Раздел 1 · Постановка задачи', title: 'Цели и задачи проекта',
    meta: 'КОНТЕКСТ',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'goals',
  },

  // ============= AS IS / TO BE BPMN =============
  { kind: 'divider', label: '04 Моделирование — Раздел',
    section: '02', sectionLbl: 'Раздел 2',
    title: 'Моделирование процессов<br>AS IS · TO BE',
    dots: ['BPMN-нотация', 'Текущий процесс', 'Целевой процесс', '7 моделей'] },

  {
    kind: 'bpmn', label: '05 AS IS текущий',
    eyebrow: 'AS IS · Текущий процесс',
    title: 'Текущий бумажный процесс организации пересдачи',
    meta: 'AS IS',
    lead: 'Действующий процесс собран на интервью с работниками кафедры, преподавателями и учебным отделом. Видны 4 дорожки участников и десятки шагов на бумаге.',
    tags: ['AS IS', '4 дорожки', '~24 шагов', 'бумага и устные договорённости'],
    img: 'assets/image-4-1.jpeg',
    foot: { l: 'BPMN · полный процесс', r: '' },
  },
  {
    kind: 'bpmn', label: '06 AS IS проблемы',
    eyebrow: 'AS IS · Узкие места', title: 'Узкие места и неэффективности текущего процесса',
    meta: 'AS IS · УЗКИЕ МЕСТА',
    lead: 'На той же модели подсвечены точки потерь: ручные согласования, отсутствие синхронизации между ролями и потерянные документы.',
    tags: ['ручные согласования', 'нет синхронизации', 'утечка документов', 'нет аудита'],
    img: 'assets/image-5-1.jpeg',
    foot: { l: 'BPMN · точки потерь', r: '' },
  },
  {
    kind: 'bpmn', label: '07 TO BE Создание расписания',
    eyebrow: 'TO BE · Целевой процесс', title: 'Создание и согласование слотов пересдач',
    meta: 'TO BE · ШАГ 1',
    lead: 'Целевая модель: преподаватель задаёт доступность → кафедра создаёт черновики → завкафедрой утверждает → учебный отдел публикует. Каждый шаг — действие в системе.',
    tags: ['доступность', 'черновик', 'утверждение', 'публикация'],
    img: 'assets/image-6-1.jpeg',
    foot: { l: 'BPMN · процесс создания расписания', r: '' },
  },

  {
    kind: 'bpmn', label: '08 TO BE Запись — часть 1',
    eyebrow: 'TO BE · Целевой процесс', title: 'Запись студента — поиск и выбор слота',
    meta: 'TO BE · ШАГ 2.1',
    lead: 'Студент видит свои долги, открывает доступные слоты по нужной дисциплине и оценивает аудиторию, время и количество мест.',
    tags: ['ЛКС', 'выбор слота', 'фильтры', 'свободные места'],
    img: 'assets/image-7-1.jpeg',
    foot: { l: 'BPMN · сценарий записи (1/2)', r: '' },
  },
  {
    kind: 'bpmn', label: '09 TO BE Запись — часть 2',
    eyebrow: 'TO BE · Целевой процесс', title: 'Запись студента — серверная проверка и подтверждение',
    meta: 'TO BE · ШАГ 2.2',
    lead: 'Сервер проверяет BR-01 (≥ 12 ч до пересдачи), наличие мест, отсутствие конфликтов в iCal и фиксирует запись с пометкой источника self.',
    tags: ['BR-01 ≥ 12 ч', 'конфликты iCal', 'enrollments', 'audit log'],
    img: 'assets/image-7-2.jpeg',
    foot: { l: 'BPMN · сценарий записи (2/2)', r: '' },
  },

  {
    kind: 'bpmn', label: '10 TO BE Проведение — часть 1',
    eyebrow: 'TO BE · Целевой процесс', title: 'Проведение пересдачи — список и оценка',
    meta: 'TO BE · ШАГ 3.1',
    lead: 'В день пересдачи преподаватель открывает свой список и проставляет оценки каждому студенту с фиксацией явки.',
    tags: ['список группы', 'оценка 2–5', 'явка', 'комментарий'],
    img: 'assets/image-8-1.jpeg',
    foot: { l: 'BPMN · оценка студентов', r: '' },
  },
  {
    kind: 'bpmn', label: '11 TO BE Проведение — часть 2',
    eyebrow: 'TO BE · Целевой процесс', title: 'Проведение пересдачи — фиксация результата',
    meta: 'TO BE · ШАГ 3.2',
    lead: 'Результат проходит через сервис: при оценке ≥ 3 — долг автоматически закрывается (BR-03), запись получает статус completed, действие пишется в AuditLog.',
    tags: ['BR-03', 'auto close debt', 'completed', 'audit'],
    img: 'assets/image-8-2.jpeg',
    foot: { l: 'BPMN · фиксация результата', r: '' },
  },

  {
    kind: 'bpmn', label: '12 TO BE Результат — часть 1',
    eyebrow: 'TO BE · Целевой процесс', title: 'Результат — уведомление студента',
    meta: 'TO BE · ШАГ 4.1',
    lead: 'После фиксации результата система рассылает уведомление студенту и обновляет статус задолженности в его кабинете.',
    tags: ['notifications', 'closed/active', 'статус долга'],
    img: 'assets/image-9-1.jpeg',
    foot: { l: 'BPMN · уведомление студента', r: '' },
  },
  {
    kind: 'bpmn', label: '13 TO BE Результат — часть 2',
    eyebrow: 'TO BE · Целевой процесс', title: 'Результат — отчётность и аудит',
    meta: 'TO BE · ШАГ 4.2',
    lead: 'Учебный отдел получает итоговую ведомость по пересдаче, любые действия — в журнале аудита с временной меткой и пользователем.',
    tags: ['ведомость', 'аудит', 'учебный отдел'],
    img: 'assets/image-9-2.jpeg',
    foot: { l: 'BPMN · отчёт и аудит', r: '' },
  },

  {
    kind: 'bpmn', label: '14 TO BE Администрирование',
    eyebrow: 'TO BE · Целевой процесс', title: 'Администрирование пользователей и данных',
    meta: 'TO BE · АДМИНИСТРИРОВАНИЕ',
    lead: 'Параллельный процесс: администратор управляет пользователями, ролями, долгами и любыми сущностями с полным аудитом изменений.',
    tags: ['admin', 'soft delete', 'history', 'audit'],
    img: 'assets/image-10-1.jpeg',
    foot: { l: 'BPMN · администрирование системы', r: '' },
  },

  // ============= АРХИТЕКТУРА =============
  { kind: 'divider', label: '15 Архитектура — Раздел',
    section: '03', sectionLbl: 'Раздел 3',
    title: 'Архитектура<br>и технологический стек',
    dots: ['NestJS · React · PostgreSQL', 'Монорепо', '3 приложения', 'JWT + RBAC'] },

  {
    kind: 'content', label: '16 Технологический стек',
    eyebrow: 'Раздел 3 · Архитектура', title: 'Технологический стек', meta: 'СТЕК',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'stack',
  },
  {
    kind: 'content', label: '17 Архитектура системы',
    eyebrow: 'Раздел 3 · Архитектура',
    title: '3 приложения, единый API и интеграции с МИРЭА',
    meta: 'АРХИТЕКТУРА',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'architecture',
  },
  {
    kind: 'content', label: '18 Монорепозиторий',
    eyebrow: 'Раздел 3 · Архитектура', title: 'Монорепозиторий — Turborepo + pnpm workspaces',
    meta: 'МОНОРЕПО',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'monorepo',
  },

  // ============= ЛКС =============
  { kind: 'divider', label: '19 ЛКС — Раздел',
    section: '04', sectionLbl: 'Раздел 4',
    title: 'Личный кабинет<br>студента — ЛКС',
    dots: ['SSO · локальный · 2FA', 'Долги и пересдачи', 'Запись в один клик'] },

  {
    kind: 'content', label: '20 ЛКС возможности',
    eyebrow: 'Раздел 4 · Личный кабинет студента', title: 'Что умеет ЛКС',
    meta: 'ЛКС · ВОЗМОЖНОСТИ',
    foot: { l: 'РТУ МИРЭА · Система пересдач', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'lks-features',
  },

  // ============= ЛКС screenshots — one per slide =============
  // SSO + 2FA — это одна система, объединена в один слайд с двумя скриншотами
  {
    kind: 'shot-dual',
    label: '21 ЛКС Вход — MIREA SSO и 2FA',
    meta: 'ЛКС · ВХОД · MIREA SSO',
    eyebrow: 'Раздел 4 · ЛКС · Вход',
    sectionTitle: 'MIREA SSO — вход для всех студентов',
    images: [
      { src: 'assets/image-15-1.png', url: 'lks.mirea.ru/login', caption: 'Шаг 1 · форма SSO' },
      { src: 'assets/image-15-2.png', url: 'sso.mirea.ru/.../auth?2fa', caption: 'Шаг 2 · 2FA через Keycloak' },
    ],
    side: {
      what: 'ЕДИНЫЙ ВХОД',
      heading: 'Один поток — SSO с 2FA',
      lead: 'Студент авторизуется институтским логином через sso.mirea.ru. Если в Keycloak включена 2FA — после пароля запрашивается одноразовый код.',
      bullets: [
        '<b>OpenID Connect</b> · PKCE без client_secret',
        '<code>code_verifier</code> (64 байта) → <code>code_challenge</code> = SHA-256',
        '<code>POST /auth/mirea/login</code> → <code>/auth/mirea/otp</code> при 2FA',
        'После входа — <code>gRPC GetMeInfo</code> на attendance.mirea.ru за ФИО',
      ],
      stampN: '1', stampT: 'Способ 1 из 2 · Аутентификация',
    },
    foot: { l: 'Авторизация студента · SSO', r: 'sso.mirea.ru · OpenID PKCE + 2FA' },
  },
  shot({ label: '22 ЛКС Вход — локальный аккаунт', meta: 'ЛКС · ВХОД · ЛОКАЛЬНО', rev: true,
    eyebrow: 'Раздел 4 · ЛКС · Вход', sectionTitle: 'Локальный вход — для тестов и сервиса',
    img: 'assets/lks-login-local.png', url: 'lks.mirea.ru/login?mode=local',
    side: {
      what: 'СПОСОБ 2',
      heading: 'Email + пароль, отдельно от МИРЭА',
      lead: 'Резервный способ для тестовых аккаунтов и служебных пользователей. Не зависит от sso.mirea.ru и работает даже когда SSO недоступен.',
      bullets: [
        'Пароль хранится как <code>bcrypt</code>-хэш',
        '<code>POST /auth/login</code> → тот же JWT, что и SSO',
        'Тестовые аккаунты: <code>student01..15@mirea.ru</code>, <code>teacher@mirea.ru</code>, <code>admin@mirea.ru</code>',
        'RolesGuard работает одинаково — права не зависят от способа входа',
      ],
      stampN: '2', stampT: 'Способ 2 из 2 · Аутентификация',
    },
    foot: { l: 'Резервный вход', r: 'bcrypt · service-аккаунты' },
  }),

  shot({ label: '23 ЛКС Долги — внутренняя БД', meta: 'ЛКС · ЗАДОЛЖЕННОСТИ',
    eyebrow: 'Раздел 4 · ЛКС · Долги', sectionTitle: 'Долги из внутренней базы',
    img: 'assets/image-16-1.png', url: 'lks.mirea.ru/debts',
    side: {
      what: 'ИСТОЧНИК 1',
      heading: 'Авторитетные долги из БД системы',
      lead: 'Записи Debt создаются учебным отделом и администратором. Кнопка «Записаться» сразу ведёт на ближайшие доступные слоты.',
      bullets: [
        'Статусы <code>active</code> · <code>closed</code> · <code>unresolved</code>',
        'Подсветка дисциплин с приближающимся дедлайном',
        'Авто-закрытие при оценке ≥ 3 (BR-03)',
      ],
      stampN: '1', stampT: 'Источник 1 из 2',
    },
    foot: { l: 'Источник 1', r: 'таблица Debt в PostgreSQL' },
  }),
  shot({ label: '24 ЛКС Долги — lk.mirea.ru', meta: 'ЛКС · ЗАДОЛЖЕННОСТИ', rev: true,
    eyebrow: 'Раздел 4 · ЛКС · Долги', sectionTitle: 'Долги с lk.mirea.ru — live',
    img: 'assets/image-16-2.png', url: 'lks.mirea.ru/debts?source=lk.mirea.ru',
    side: {
      what: 'ИСТОЧНИК 2',
      heading: 'Парсинг живых данных с lk.mirea.ru',
      lead: 'Параллельно сервер открывает SSO-сессию в Bitrix-ЛК, проходит 7-шаговый редирект и парсит HTML-таблицу долгов.',
      bullets: [
        'Эмуляция браузерной сессии · <code>SimpleCookieJar</code>',
        'Маршрут редиректов: SSO → ЛК → selectStudentProfile',
        'Кэш на 5 минут, чтобы не нагружать lk.mirea.ru',
      ],
      stampN: '2', stampT: 'Источник 2 из 2',
    },
    foot: { l: 'Источник 2', r: 'lk.mirea.ru · HTML-парсинг' },
  }),

  shot({ label: '25 ЛКС Поиск расписания — по группе', meta: 'ЛКС · РАСПИСАНИЕ',
    eyebrow: 'Раздел 4 · ЛКС · Расписание МИРЭА', sectionTitle: 'Поиск расписания по группе',
    img: 'assets/image-17-1.png', url: 'lks.mirea.ru/schedule?type=group',
    side: {
      what: 'ИСТОЧНИК ДАННЫХ',
      heading: 'Расписание тянем по API из МИРЭА',
      lead: 'Студент ищет свою группу — выпадает список найденных по подстроке. Данные приходят с <code>schedule-of.mirea.ru</code>, кэшируются на 24 часа.',
      bullets: [
        '<code>GET /api/mirea-schedule/search?q=УИБО</code>',
        'Синхронизация раз в 24 ч (<code>MIREA_SCHEDULE_SYNC_INTERVAL_HOURS</code>)',
        'Поиск охватывает группы, преподавателей и аудитории',
        'Хранение в <code>MireaScheduleItem</code> с <code>iCalLink</code>',
      ],
      stampN: '1', stampT: 'Поиск по группе',
    },
    foot: { l: 'Поиск расписания', r: 'schedule-of.mirea.ru · iCal · 24 ч кэш' },
  }),
  shot({ label: '26 ЛКС Поиск расписания — преподаватели и аудитории', meta: 'ЛКС · РАСПИСАНИЕ', rev: true,
    eyebrow: 'Раздел 4 · ЛКС · Расписание МИРЭА', sectionTitle: 'Поиск — преподаватели, аудитории',
    img: 'assets/image-17-2.png', url: 'lks.mirea.ru/schedule?q=Морозов',
    side: {
      what: 'УНИВЕРСАЛЬНЫЙ ПОИСК',
      heading: 'Группа, преподаватель или аудитория',
      lead: 'Тот же эндпоинт ищет по любому типу: группа УИБО-05-23, преподаватель «Морозов», аудитория «А-103». В выдаче — тип сущности и название.',
      bullets: [
        'Тип сущности: <code>group</code> / <code>teacher</code> / <code>room</code>',
        'iCal-фид расписания подгружается по клику',
        '<code>GET /api/mirea-schedule/disciplines/:id/teachers</code>',
        'Эти же данные нужны системе для проверки конфликтов слотов',
      ],
      stampN: '2', stampT: 'Универсальный поиск',
    },
    foot: { l: 'Поиск по преподавателю / аудитории', r: '/api/mirea-schedule/search' },
  }),

  shot({ label: '27 ЛКС Запись — выбор слота', meta: 'ЛКС · ЗАПИСЬ',
    eyebrow: 'Раздел 4 · ЛКС · Запись на пересдачу', sectionTitle: 'Шаг 1 · Выбор слота',
    img: 'assets/image-18-1.png', url: 'lks.mirea.ru/retakes/enroll?step=1',
    side: {
      what: 'ШАГ 1',
      heading: 'Студент выбирает удобный слот',
      lead: 'Из списка доступных слотов студент кликает «Записаться» — открывается модальное окно подтверждения.',
      bullets: ['Свободные слоты подсвечены синим', 'Полные — серым, недоступным', 'Видно количество мест: 12/20'],
      stampN: '1', stampT: 'Шаг 1 из 3',
    },
    foot: { l: 'Запись · шаг 1', r: 'выбор слота' },
  }),
  shot({ label: '28 ЛКС Запись — подтверждение', meta: 'ЛКС · ЗАПИСЬ', rev: true,
    eyebrow: 'Раздел 4 · ЛКС · Запись на пересдачу', sectionTitle: 'Шаг 2 · Подтверждение',
    img: 'assets/image-18-2.png', url: 'lks.mirea.ru/retakes/enroll?step=2',
    side: {
      what: 'ШАГ 2',
      heading: 'Серверная проверка и подтверждение',
      lead: 'Перед записью сервер проверяет BR-01 (≥ 12 ч до начала), наличие мест и отсутствие дубликатов записи.',
      bullets: [
        '<code>POST /enrollments</code> · идемпотентно',
        '422 Unprocessable, если правила нарушены',
        'Транзакция в одном запросе',
      ],
      stampN: '2', stampT: 'Шаг 2 из 3',
    },
    foot: { l: 'Запись · шаг 2', r: 'проверка BR-01' },
  }),
  shot({ label: '29 ЛКС Запись — повторная запись запрещена', meta: 'ЛКС · ЗАПИСЬ',
    eyebrow: 'Раздел 4 · ЛКС · Запись на пересдачу', sectionTitle: 'Шаг 3 · Повторная запись запрещена',
    img: 'assets/image-18-3.png', url: 'lks.mirea.ru/retakes/enroll?step=3',
    side: {
      what: 'ALREADY_ENROLLED',
      heading: 'Нельзя записаться дважды на ту же пересдачу',
      lead: 'Внизу карточки — статусная подпись «Вы уже записаны на пересдачу». Сервер вернёт ошибку <code>ALREADY_ENROLLED</code>, кнопка «Записаться» неактивна.',
      bullets: [
        'Проверка <code>EnrollmentsService.enroll()</code>',
        'Коды ошибок: <code>NO_DEBT · ALREADY_ENROLLED · SLOT_FULL · TOO_LATE · NO_RIGHT</code>',
        'Защита от дублей даже при двойном клике',
        'AuditLog не пишется — действие отклонено до создания записи',
      ],
      stampN: '3', stampT: 'Шаг 3 из 3 · Защита от дублей',
    },
    foot: { l: 'Идемпотентность записи', r: 'EnrollmentError.reason = ALREADY_ENROLLED' },
  }),

  shot({ label: '30 ЛКС Мои пересдачи', meta: 'ЛКС · МОИ ПЕРЕСДАЧИ',
    eyebrow: 'Раздел 4 · ЛКС · Мои пересдачи', sectionTitle: 'Хронология всех записей',
    img: 'assets/image-19-1.png', url: 'lks.mirea.ru/learning/retakes',
    side: {
      what: 'ИСТОРИЯ',
      heading: 'Все мои пересдачи и их статусы',
      lead: 'Простая таблица: дисциплина, дата, статус. Цветовой раскраски нет — статусы текстовые, читаемые с первого взгляда.',
      bullets: [
        '<code>enrolled</code> · «Записан», ждём пересдачу',
        '<code>completed</code> · оценка получена',
        '<code>absent</code> · «Не явился», фиксируется в аудите',
        'Источник: <code>GET /api/enrollments/my</code>',
      ],
      stampN: 'Σ', stampT: '3 возможных статуса',
    },
    foot: { l: 'История записей', r: '/api/enrollments/my' },
  }),

  // ============= ЛКП =============
  { kind: 'divider', label: 'ЛКП — Раздел',
    section: '05', sectionLbl: 'Раздел 5',
    title: 'Портал персонала<br>ЛКП — 6 ролей RBAC',
    dots: ['Преподаватель', 'Кафедра', 'Учебный отдел', 'Администратор'] },

  {
    kind: 'content', label: 'ЛКП — 6 ролей',
    eyebrow: 'Раздел 5 · Портал персонала',
    title: '6 ролей RBAC — кто и что делает',
    meta: 'ЛКП · 6 РОЛЕЙ',
    foot: { l: 'Ролевая модель', r: 'RBAC · @Roles() + RolesGuard' },
    body: 'rbac-roles',
  },

  // Teacher
  shot({ label: 'ЛКП Преподаватель — доступность (список)', meta: 'ЛКП · TEACHER',
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Доступность — список интервалов',
    img: 'assets/image-21-1.png', url: 'lkp.mirea.ru/teacher/availability',
    side: {
      what: 'ШАГ 0 · ВХОД В ЦИКЛ',
      heading: 'Преподаватель отмечает свободное время',
      lead: 'Это стартовая точка процесса. Без указания доступности кафедра не сможет создать черновик слота.',
      bullets: ['Список интервалов с фильтром по неделе', 'Видно занятые часы из расписания МИРЭА', 'Один клик — открыть форму добавления'],
      stampN: '1', stampT: 'Доступность · просмотр',
    },
    foot: { l: 'TeacherAvailability', r: 'старт цикла пересдачи' },
  }),
  shot({ label: 'ЛКП Преподаватель — доступность (редактирование)', meta: 'ЛКП · TEACHER', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Доступность — форма интервала',
    img: 'assets/image-21-2.png', url: 'lkp.mirea.ru/teacher/availability/edit',
    side: {
      what: 'РЕДАКТИРОВАНИЕ',
      heading: 'Форма интервала с проверкой конфликтов',
      lead: 'При сохранении сервер сверяет интервал с iCal-фидом расписания преподавателя и предупреждает о пересечениях.',
      bullets: ['Сравнение с <code>VEVENT</code> из расписания', 'Запрет интервалов внутри занятий', 'Сохранение в TeacherAvailability'],
      stampN: '2', stampT: 'Доступность · редактирование',
    },
    foot: { l: 'Форма интервала', r: 'iCal · конфликты VEVENT' },
  }),

  shot({ label: 'ЛКП Преподаватель — расписание', meta: 'ЛКП · TEACHER',
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Расписание — занятия',
    img: 'assets/image-22-1.png', url: 'lkp.mirea.ru/teacher/schedule',
    side: {
      what: 'РАСПИСАНИЕ',
      heading: 'Сначала — обычные пары',
      lead: 'Привычная сетка из расписания МИРЭА — синхронизируется с schedule-of.mirea.ru каждые 24 часа.',
      bullets: ['Календарь на месяц с навигацией', 'Цветовая шкала загрузки дня', 'Импорт iCal-фида'],
      stampN: '1', stampT: 'Обычные занятия',
    },
    foot: { l: 'Расписание', r: 'iCal · 24 ч TTL кэша' },
  }),
  shot({ label: 'ЛКП Преподаватель — расписание со слотами', meta: 'ЛКП · TEACHER', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Расписание со слотами пересдач',
    img: 'assets/image-22-2.png', url: 'lkp.mirea.ru/teacher/schedule?view=retakes',
    side: {
      what: 'ПЕРЕСДАЧИ',
      heading: 'Те же даты, плюс свои пересдачи',
      lead: 'Слоты пересдач помечены отдельным цветом, по клику открывается список записавшихся студентов.',
      bullets: ['Свои слоты подсвечены бирюзовым', 'Кол-во записавшихся прямо в ячейке', 'Кнопка «Провести пересдачу»'],
      stampN: '2', stampT: 'Расписание + пересдачи',
    },
    foot: { l: 'Слоты в расписании', r: 'view=retakes' },
  }),

  shot({ label: 'ЛКП Преподаватель — список пересдач', meta: 'ЛКП · TEACHER',
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Список ближайших пересдач',
    img: 'assets/image-23-1.png', url: 'lkp.mirea.ru/teacher/retakes',
    side: {
      what: 'СПИСОК',
      heading: 'Все мои пересдачи в одном экране',
      lead: 'Фильтр «требуют внимания» показывает слоты, у которых пора зафиксировать результат.',
      bullets: ['Сортировка по дате и статусу', 'Фильтр «требуют внимания»', 'Быстрый переход к проведению'],
      stampN: '★', stampT: 'Дашборд преподавателя',
    },
    foot: { l: 'Список пересдач преподавателя', r: 'все статусы слотов' },
  }),

  shot({ label: 'ЛКП Преподаватель — проведение, шаг 1', meta: 'ЛКП · TEACHER',
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Проведение · шаг 1 — открыть слот',
    img: 'assets/image-24-1.png', url: 'lkp.mirea.ru/teacher/retakes/#42/run',
    side: {
      what: 'ШАГ 1',
      heading: 'Открыть слот в день пересдачи',
      lead: 'В карточке — список записавшихся, аудитория и время. Если кто-то не пришёл, его помечают как absent.',
      bullets: ['Видно количество мест: 1/20', 'Список студентов с группой и долгом', 'Кнопка «Начать оценивание»'],
      stampN: '1', stampT: 'Шаг 1 из 3',
    },
    foot: { l: 'Проведение · шаг 1', r: 'открытие слота' },
  }),
  shot({ label: 'ЛКП Преподаватель — проведение, шаг 2', meta: 'ЛКП · TEACHER', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Проведение · шаг 2 — оценка',
    img: 'assets/image-24-2.png', url: 'lkp.mirea.ru/teacher/retakes/#42/grade',
    side: {
      what: 'ШАГ 2',
      heading: 'Оценка и фиксация явки',
      lead: 'Преподаватель выставляет оценку 2–5, отмечает явку, добавляет комментарий.',
      bullets: ['Оценка 2–5 или «Не явился»', 'Поле комментария (опционально)', '<code>POST /results</code> на каждого студента'],
      stampN: '2', stampT: 'Шаг 2 из 3',
    },
    foot: { l: 'Проведение · шаг 2', r: 'оценивание' },
  }),
  shot({ label: 'ЛКП Преподаватель — проведение, шаг 3', meta: 'ЛКП · TEACHER',
    eyebrow: 'Раздел 5 · ЛКП · teacher', sectionTitle: 'Проведение · шаг 3 — фиксация',
    img: 'assets/image-24-3.png', url: 'lkp.mirea.ru/teacher/retakes/#42/done',
    side: {
      what: 'ШАГ 3',
      heading: 'Зафиксировать результат',
      lead: 'По кнопке «Зафиксировать»: при оценке ≥ 3 долг автоматически закрывается (BR-03), запись становится <code>completed</code>, всё пишется в аудит.',
      bullets: ['BR-03 — авто-закрытие долга', 'Статус enrollment → <code>completed</code>', 'AuditLog action = RECORD_RESULT'],
      stampN: '3', stampT: 'Шаг 3 из 3',
    },
    foot: { l: 'Проведение · шаг 3', r: 'BR-03 · автозакрытие' },
  }),

  // dept_worker
  shot({ label: 'ЛКП Кафедра — черновики, список', meta: 'ЛКП · DEPT_WORKER',
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Черновики слотов — список',
    img: 'assets/image-25-1.png', url: 'lkp.mirea.ru/dept/drafts',
    side: {
      what: 'ШАГ 1',
      heading: 'Сотрудник кафедры ведёт черновики',
      lead: 'Используются доступности преподавателей: для каждой дисциплины собираются группы и создаются слоты-черновики.',
      bullets: ['Фильтр по дисциплине и преподавателю', 'Статусы <code>draft</code> · <code>rejected</code>', 'Кнопка «+ Слот»'],
      stampN: '1', stampT: 'Шаг 1 · Список черновиков',
    },
    foot: { l: 'Черновики', r: 'status=draft' },
  }),
  shot({ label: 'ЛКП Кафедра — черновики, форма', meta: 'ЛКП · DEPT_WORKER', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Черновик — заполнение полей',
    img: 'assets/image-25-2.png', url: 'lkp.mirea.ru/dept/drafts/new',
    side: {
      what: 'ШАГ 2',
      heading: 'Дисциплина, преподаватель, дата',
      lead: 'Автозаполнение: при выборе преподавателя подгружаются его доступные интервалы; аудитории фильтруются по корпусу.',
      bullets: ['Подсказки по преподавателям', 'Поиск аудитории по корпусу/этажу', 'Проверка max_students против правил'],
      stampN: '2', stampT: 'Шаг 2 · Форма',
    },
    foot: { l: 'Форма черновика', r: 'автозаполнение из доступности' },
  }),
  shot({ label: 'ЛКП Кафедра — черновики, конфликты', meta: 'ЛКП · DEPT_WORKER',
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Серверная проверка конфликтов',
    img: 'assets/image-25-3.png', url: 'lkp.mirea.ru/dept/drafts/new?conflict',
    side: {
      what: 'ШАГ 3',
      heading: 'Проверка конфликтов в реальном времени',
      lead: 'При сохранении сервер сверяет дату/аудиторию с iCal-фидом и существующими слотами. Если есть конфликт — 400 c описанием.',
      bullets: ['Проверка <code>VEVENT</code> в iCal', 'Поиск пересечений по аудитории', 'Подсказка: «занят с 16:20 до 17:50»'],
      stampN: '3', stampT: 'Шаг 3 · Конфликты',
    },
    foot: { l: 'Конфликты iCal', r: '400 Bad Request с описанием' },
  }),

  shot({ label: 'ЛКП Кафедра — черновики, отправка 1', meta: 'ЛКП · DEPT_WORKER',
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Сохранение черновика',
    img: 'assets/image-26-1.png', url: 'lkp.mirea.ru/dept/drafts/new/saved',
    side: {
      what: 'ШАГ 4',
      heading: 'Черновик сохранён',
      lead: 'После успешной валидации слот появляется в общем списке черновиков со статусом <code>draft</code>.',
      bullets: ['Сразу видно в общем списке', 'Можно редактировать пока draft', 'Аудит — action = CREATE_DRAFT_SLOT'],
      stampN: '4', stampT: 'Шаг 4 · Сохранение',
    },
    foot: { l: 'Черновик сохранён', r: 'status=draft' },
  }),
  shot({ label: 'ЛКП Кафедра — черновики, проверка', meta: 'ЛКП · DEPT_WORKER', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Сводка перед отправкой',
    img: 'assets/image-26-2.png', url: 'lkp.mirea.ru/dept/drafts/#7/review',
    side: {
      what: 'ШАГ 5',
      heading: 'Финальная сводка',
      lead: 'Перед отправкой завкафедрой сотрудник видит полную карточку: преподаватель, доступность, аудитория, ожидаемые студенты.',
      bullets: ['Сводка по полям', 'Превью карточки в ЛКС', 'История действий по черновику'],
      stampN: '5', stampT: 'Шаг 5 · Сводка',
    },
    foot: { l: 'Финальная проверка', r: 'перед отправкой' },
  }),
  shot({ label: 'ЛКП Кафедра — черновики, отправка завкафедрой', meta: 'ЛКП · DEPT_WORKER',
    eyebrow: 'Раздел 5 · ЛКП · dept_worker', sectionTitle: 'Отправка на утверждение',
    img: 'assets/image-26-3.png', url: 'lkp.mirea.ru/dept/drafts/#7/submit',
    side: {
      what: 'ШАГ 6',
      heading: 'Передача завкафедрой',
      lead: 'Кнопка «Отправить на утверждение» меняет статус и кладёт уведомление в очередь завкафедры. С этого момента редактировать нельзя.',
      bullets: ['Статус: <code>draft → pending</code>', 'Уведомление завкафедрой', 'Запись в AuditLog · SUBMIT_DRAFT'],
      stampN: '6', stampT: 'Шаг 6 · Передача',
    },
    foot: { l: 'Передано завкафедрой', r: 'status=pending' },
  }),

  // dept_head
  shot({ label: 'ЛКП Завкафедрой — список', meta: 'ЛКП · DEPT_HEAD',
    eyebrow: 'Раздел 5 · ЛКП · dept_head', sectionTitle: 'Список на утверждение',
    img: 'assets/image-27-1.png', url: 'lkp.mirea.ru/dept-head/approvals',
    side: {
      what: 'ОЧЕРЕДЬ',
      heading: 'Что ждёт утверждения',
      lead: 'Список черновиков от сотрудников кафедры с приоритетом по дате пересдачи.',
      bullets: ['Сортировка по deadline-у пересдачи', 'Фильтр по преподавателю', 'Массовые действия — approve/reject'],
      stampN: '1', stampT: 'Шаг 1 · Очередь',
    },
    foot: { l: 'Очередь утверждения', r: 'status=pending' },
  }),
  shot({ label: 'ЛКП Завкафедрой — детали слота', meta: 'ЛКП · DEPT_HEAD', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · dept_head', sectionTitle: 'Утверждение или отклонение',
    img: 'assets/image-27-2.png', url: 'lkp.mirea.ru/dept-head/approvals/#7',
    side: {
      what: 'РЕШЕНИЕ',
      heading: 'Approve / Reject с комментарием',
      lead: 'В карточке всё для решения: преподаватель, нагрузка, конфликты, история правок. Отклонение — с обязательным комментарием.',
      bullets: ['Статусы: <code>approved</code> · <code>rejected</code>', 'Комментарий — виден кафедре', 'AuditLog · APPROVE/REJECT_DRAFT'],
      stampN: '2', stampT: 'Шаг 2 · Решение',
    },
    foot: { l: 'Утверждение/отклонение', r: 'фиксируется в аудите' },
  }),

  // academic_office
  shot({ label: 'ЛКП Учебный отдел — публикация', meta: 'ЛКП · ACADEMIC_OFFICE',
    eyebrow: 'Раздел 5 · ЛКП · academic_office', sectionTitle: 'Публикация расписания',
    img: 'assets/image-28-1.png', url: 'lkp.mirea.ru/academic/publish',
    side: {
      what: 'ПУБЛИКАЦИЯ',
      heading: 'Готовые к публикации слоты',
      lead: 'Учебный отдел просматривает утверждённые слоты по факультетам и публикует их пакетом или поштучно.',
      bullets: ['Группировка по неделям', 'Превью того, что увидит студент', 'Массовая публикация'],
      stampN: '1', stampT: 'Шаг 1 · Список',
    },
    foot: { l: 'Публикация', r: 'status=approved → published' },
  }),
  shot({ label: 'ЛКП Учебный отдел — подтверждение публикации', meta: 'ЛКП · ACADEMIC_OFFICE', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · academic_office', sectionTitle: 'Подтверждение публикации',
    img: 'assets/image-28-2.png', url: 'lkp.mirea.ru/academic/publish/confirm',
    side: {
      what: 'ШАГ 2',
      heading: 'Опубликовано — видно студентам',
      lead: 'После публикации слоты становятся доступны студентам в ЛКС. Изменения шлются в систему уведомлений.',
      bullets: ['Запись в AuditLog · PUBLISH_SLOT', 'Slot.status → <code>published</code>', 'Уведомление студентов по группе'],
      stampN: '2', stampT: 'Шаг 2 · Подтверждение',
    },
    foot: { l: 'Опубликовано', r: 'видно в ЛКС' },
  }),

  shot({ label: 'ЛКП Учебный отдел — ручная запись 1', meta: 'ЛКП · ACADEMIC_OFFICE',
    eyebrow: 'Раздел 5 · ЛКП · academic_office', sectionTitle: 'Ручное зачисление — поиск студента',
    img: 'assets/image-29-1.png', url: 'lkp.mirea.ru/academic/manual',
    side: {
      what: 'ШАГ 1',
      heading: 'Поиск студента',
      lead: 'Когда студент не может записаться сам (закрытие срока, конфликт), учебный отдел делает это вручную.',
      bullets: ['Поиск по ФИО, группе, ID', 'Видна история записей студента', 'Прямой переход к долгам'],
      stampN: '1', stampT: 'Шаг 1 · Поиск',
    },
    foot: { l: 'Ручная запись', r: 'source = manual' },
  }),
  shot({ label: 'ЛКП Учебный отдел — ручная запись 2', meta: 'ЛКП · ACADEMIC_OFFICE', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · academic_office', sectionTitle: 'Ручное зачисление — выбор слота',
    img: 'assets/image-29-2.png', url: 'lkp.mirea.ru/academic/manual?stage=slot',
    side: {
      what: 'ШАГ 2',
      heading: 'Выбор подходящего слота',
      lead: 'В обход BR-01: учебный отдел может записать даже за &lt; 12 ч до пересдачи — действие требует подтверждения.',
      bullets: ['Список совместимых слотов', 'Override BR-01 с пояснением', 'Видны места и преподаватель'],
      stampN: '2', stampT: 'Шаг 2 · Выбор',
    },
    foot: { l: 'Выбор слота', r: 'возможен override BR-01' },
  }),
  shot({ label: 'ЛКП Учебный отдел — ручная запись 3', meta: 'ЛКП · ACADEMIC_OFFICE',
    eyebrow: 'Раздел 5 · ЛКП · academic_office', sectionTitle: 'Ручное зачисление — подтверждение',
    img: 'assets/image-29-3.png', url: 'lkp.mirea.ru/academic/manual?stage=confirm',
    side: {
      what: 'ШАГ 3',
      heading: 'Подтверждение и аудит',
      lead: 'Действие фиксируется с указанием причины. Студент получает уведомление, как при обычной записи.',
      bullets: ['<code>source = manual</code>', 'Обязательная причина-комментарий', 'AuditLog · MANUAL_ENROLL'],
      stampN: '3', stampT: 'Шаг 3 · Подтверждение',
    },
    foot: { l: 'Запись создана', r: 'причина в AuditLog' },
  }),

  // admin
  shot({ label: 'ЛКП Админ — пользователи, список', meta: 'ЛКП · ADMIN',
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Управление пользователями',
    img: 'assets/image-30-1.png', url: 'lkp.mirea.ru/admin/users',
    side: {
      what: 'УПРАВЛЕНИЕ ПОЛЬЗОВАТЕЛЯМИ',
      heading: 'Все аккаунты и роли',
      lead: 'Видны все пользователи: ФИО, роль, источник (SSO/локальный), последний вход, soft-deleted.',
      bullets: ['Фильтр по роли и статусу', 'Поиск по email и mireaSsoId', 'Soft delete с возможностью восстановления'],
      stampN: '1', stampT: 'Список пользователей',
    },
    foot: { l: 'Список пользователей', r: 'soft delete · история' },
  }),
  shot({ label: 'ЛКП Админ — пользователи, создание', meta: 'ЛКП · ADMIN', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Создание пользователя',
    img: 'assets/image-30-2.png', url: 'lkp.mirea.ru/admin/users/new',
    side: {
      what: 'СОЗДАНИЕ',
      heading: 'Локальный пользователь или сопоставление с SSO',
      lead: 'Можно завести локальный аккаунт или привязать существующего mireaSsoId к роли в системе.',
      bullets: ['Локальный — пароль через bcrypt', 'SSO — только привязка ID', 'Назначение роли при создании'],
      stampN: '2', stampT: 'Форма создания',
    },
    foot: { l: 'Создание пользователя', r: 'bcrypt · SSO mapping' },
  }),
  shot({ label: 'ЛКП Админ — пользователи, редактирование роли', meta: 'ЛКП · ADMIN',
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Редактирование пользователя',
    img: 'assets/image-30-3.png', url: 'lkp.mirea.ru/admin/users/#42',
    side: {
      what: 'РЕДАКТИРОВАНИЕ',
      heading: 'Смена роли и блокировка',
      lead: 'Любое изменение роли — это событие в AuditLog. История ролей хранится без удаления.',
      bullets: ['Запись в AuditLog · USER_ROLE_CHANGE', 'История изменений пользователя', 'Блокировка без удаления'],
      stampN: '3', stampT: 'Изменение пользователя',
    },
    foot: { l: 'Редактирование', r: 'AuditLog обязателен' },
  }),

  shot({ label: 'ЛКП Админ — долги, список', meta: 'ЛКП · ADMIN',
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Управление долгами — список',
    img: 'assets/image-31-1.png', url: 'lkp.mirea.ru/admin/debts',
    side: {
      what: 'ДОЛГИ',
      heading: 'Все долги студента в одном экране',
      lead: 'Администратор видит долги выбранного студента из обоих источников: внутренней БД и lk.mirea.ru.',
      bullets: ['Поиск студента по ФИО/группе', 'Источник: <code>internal</code> / <code>lk_mirea_ru</code>', 'Цветные статусы долгов'],
      stampN: '1', stampT: 'Список долгов',
    },
    foot: { l: 'Долги студента', r: 'два источника' },
  }),
  shot({ label: 'ЛКП Админ — долги, создание', meta: 'ЛКП · ADMIN', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Создание долга',
    img: 'assets/image-31-2.png', url: 'lkp.mirea.ru/admin/debts/new',
    side: {
      what: 'СОЗДАНИЕ',
      heading: 'Учебный долг вручную',
      lead: 'Поля: дисциплина, тип (зачёт / экзамен), семестр, дедлайн. Сохраняется в таблицу Debt.',
      bullets: ['Дисциплина из справочника', 'Тип долга и кол-во ECTS', 'Дедлайн — по умолчанию 21 день'],
      stampN: '2', stampT: 'Форма создания долга',
    },
    foot: { l: 'Создание долга', r: 'таблица Debt' },
  }),
  shot({ label: 'ЛКП Админ — долги, смена статуса', meta: 'ЛКП · ADMIN',
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Смена статуса долга',
    img: 'assets/image-31-3.png', url: 'lkp.mirea.ru/admin/debts/#7/status',
    side: {
      what: 'СТАТУС',
      heading: 'active / closed / unresolved',
      lead: 'Закрыть долг вручную можно только с обязательным комментарием. Авто-закрытие — через BR-03 при оценке ≥ 3.',
      bullets: ['Только админ может закрыть вручную', 'Комментарий обязателен', 'Запись в AuditLog'],
      stampN: '3', stampT: 'Смена статуса',
    },
    foot: { l: 'Изменение статуса', r: 'AuditLog · DEBT_STATUS' },
  }),
  shot({ label: 'ЛКП Админ — долги, история', meta: 'ЛКП · ADMIN', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'История долга',
    img: 'assets/image-31-4.png', url: 'lkp.mirea.ru/admin/debts/#7/history',
    side: {
      what: 'ИСТОРИЯ',
      heading: 'Полная история по долгу',
      lead: 'Видно всё: создание, попытки пересдачи, оценки, изменения статуса. Каждое событие — с user_id и timestamp.',
      bullets: ['Кто, когда, что изменил', 'Связанные enrollments и results', 'Экспорт CSV / JSON'],
      stampN: '4', stampT: 'История долга',
    },
    foot: { l: 'История', r: 'AuditLog по долгу' },
  }),

  shot({ label: 'ЛКП Админ — запись на пересдачу', meta: 'ЛКП · ADMIN',
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Запись от имени любого студента',
    img: 'assets/image-32-1.png', url: 'lkp.mirea.ru/admin/enroll',
    side: {
      what: 'СПЕЦ-РЕЖИМ',
      heading: 'Запись минуя ограничения',
      lead: 'Админ может записать любого студента на любой слот, в том числе с нарушением BR-01 и при переполнении.',
      bullets: ['Прыжок через BR-01 и max_students', 'Только с указанием причины', '<code>source = manual</code> + <code>by_admin</code>'],
      stampN: '1', stampT: 'Админ-запись',
    },
    foot: { l: 'Запись админом', r: 'override правил с причиной' },
  }),
  shot({ label: 'ЛКП Админ — журнал аудита', meta: 'ЛКП · ADMIN', rev: true,
    eyebrow: 'Раздел 5 · ЛКП · admin', sectionTitle: 'Журнал аудита',
    img: 'assets/image-32-2.png', url: 'lkp.mirea.ru/admin/audit',
    side: {
      what: 'AUDIT LOG',
      heading: 'Каждое значимое действие — здесь',
      lead: 'Сортировка по времени, фильтры по пользователю, сущности, типу действия. Полный JSON payload.',
      bullets: [
        '<code>ENROLL</code> · <code>RECORD_RESULT</code> · <code>PUBLISH_SLOT</code>',
        '<code>USER_ROLE_CHANGE</code> · <code>DEBT_STATUS</code>',
        'Экспорт CSV для отчётов учебной части',
      ],
      stampN: 'Σ', stampT: 'Журнал аудита',
    },
    foot: { l: 'Журнал аудита', r: 'все системные события' },
  }),

  // ============= ТЕХНИЧЕСКАЯ СВОДКА =============
  { kind: 'divider', label: 'Тех. аспекты — Раздел',
    section: '06', sectionLbl: 'Раздел 6',
    title: 'Технические аспекты',
    dots: ['RBAC матрица', 'Интеграции', 'База данных', 'Безопасность', 'Развёртывание'] },

  {
    kind: 'content', label: 'RBAC матрица',
    eyebrow: 'Раздел 6 · Технические аспекты',
    title: 'Ролевая модель — матрица прав доступа',
    meta: 'RBAC',
    foot: { l: 'Декларативный RBAC', r: '@Roles() декоратор + RolesGuard' },
    body: 'rbac-matrix',
  },
  {
    kind: 'content', label: 'Интеграции',
    eyebrow: 'Раздел 6 · Технические аспекты',
    title: 'Четыре интеграции с инфраструктурой МИРЭА',
    meta: 'ИНТЕГРАЦИИ',
    foot: { l: 'Глубокая интеграция', r: 'не рядом с МИРЭА — внутри' },
    body: 'integrations',
  },
  {
    kind: 'content', label: 'БД сущности',
    eyebrow: 'Раздел 6 · Технические аспекты',
    title: 'База данных — ключевые сущности',
    meta: 'БАЗА ДАННЫХ',
    foot: { l: '8 TypeORM-сущностей', r: 'общий пакет @mirea/types' },
    body: 'db',
  },
  {
    kind: 'content', label: 'Безопасность',
    eyebrow: 'Раздел 6 · Технические аспекты',
    title: 'Безопасность — JWT, Guards, аудит',
    meta: 'БЕЗОПАСНОСТЬ',
    foot: { l: 'Многоуровневая защита', r: 'JWT · PKCE · bcrypt · audit' },
    body: 'security',
  },
  {
    kind: 'content', label: 'Развёртывание',
    eyebrow: 'Раздел 6 · Технические аспекты',
    title: 'Запуск, команды и переменные окружения',
    meta: 'DEPLOY',
    foot: { l: 'Monorepo · Turbo dev/build', r: 'pnpm dev · одна команда' },
    body: 'deploy',
  },

  // ============= ИТОГИ =============
  { kind: 'divider', label: 'Итоги — Раздел',
    section: '07', sectionLbl: 'Раздел 7',
    title: 'Итоги работы',
    dots: ['Что сделано', 'Результаты', 'Направления развития'] },

  {
    kind: 'content', label: 'Итоги — что реализовано',
    eyebrow: 'Раздел 7 · Итоги работы', title: 'Что реализовано',
    meta: 'ИТОГИ',
    foot: { l: 'Полнофункциональная платформа', r: 'от доступности до результата — без бумаги' },
    body: 'summary',
  },
  {
    kind: 'content', label: 'Результаты и направления развития',
    eyebrow: 'Раздел 7 · Итоги работы', title: 'Результаты и направления развития',
    meta: 'ВЫВОДЫ',
    foot: { l: 'Курсовой проект РТУ МИРЭА', r: 'Юшков А. Д. · УИБО-05-23 · 2026' },
    body: 'outcomes',
  },

  // ============= СПАСИБО =============
  { kind: 'thanks', label: 'Спасибо' },
];

// Helper for screenshot slides
function shot(s) { return { kind: 'shot', ...s }; }
